Repository Mango-Butter/dev-back, pull requests merged in 2025-06, with the labels that each got.

#98 [#96] 알바생 계좌 삭제 기능 개발
  app/src/main/java/com/mangoboss/app/api/controller/staff/StaffStaffController.java
  app/src/main/java/com/mangoboss/app/api/facade/staff/StaffStaffFacade.java
  app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
  app/src/main/java/com/mangoboss/app/domain/service/payroll/PayrollService.java
  app/src/main/java/com/mangoboss/app/domain/service/staff/StaffService.java
  storage/src/main/java/com/mangoboss/storage/payroll/PayrollEntity.java
  storage/src/main/java/com/mangoboss/storage/staff/StaffEntity.java
Labels: feat

#102 [#100] 매장 정보 조회 response에 알바생 정보 추가
  app/src/main/java/com/mangoboss/app/dto/store/response/StaffStoreInfoResponse.java
Labels: refactor

#103 [#100] 프론트 dto 추가 요구사항 반영
  app/src/main/java/com/mangoboss/app/api/controller/store/StaffStoreController.java
  app/src/main/java/com/mangoboss/app/api/facade/store/StaffStoreFacade.java
  app/src/main/java/com/mangoboss/app/domain/repository/StaffRepository.java
  app/src/main/java/com/mangoboss/app/domain/repository/StoreRepository.java
  app/src/main/java/com/mangoboss/app/domain/service/staff/StaffService.java
  app/src/main/java/com/mangoboss/app/domain/service/store/StoreService.java
  app/src/main/java/com/mangoboss/app/dto/store/response/StaffStoreInfoResponse.java
  app/src/main/java/com/mangoboss/app/dto/store/response/StaffStoreItemResponse.java
  app/src/main/java/com/mangoboss/app/infra/persistence/StaffRepositoryImpl.java
  app/src/main/java/com/mangoboss/app/infra/persistence/StoreRepositoryImpl.java
  storage/src/main/java/com/mangoboss/storage/staff/StaffJpaRepository.java
  storage/src/main/java/com/mangoboss/storage/store/StoreJpaRepository.java
Labels: refactor

#105 [#104] 근태 변경/대타 요청 알림 추가
  app/src/main/java/com/mangoboss/app/api/facade/attendance/BossAttendanceFacade.java
  app/src/main/java/com/mangoboss/app/api/facade/attendance/StaffAttendanceFacade.java
  app/src/main/java/com/mangoboss/app/api/facade/contract/BossContractFacade.java
  app/src/main/java/com/mangoboss/app/api/facade/schedule/BossScheduleFacade.java
  app/src/main/java/com/mangoboss/app/api/facade/schedule/StaffScheduleFacade.java
  app/src/main/java/com/mangoboss/app/domain/service/attendance/AttendanceEditService.java
  app/src/main/java/com/mangoboss/app/domain/service/notification/NotificationService.java
  app/src/main/java/com/mangoboss/app/domain/service/schedule/SubstituteRequestService.java
  storage/src/main/java/com/mangoboss/storage/attendance/AttendanceEditEntity.java
  storage/src/main/java/com/mangoboss/storage/notification/NotificationType.java
  storage/src/main/java/com/mangoboss/storage/schedule/SubstituteRequestEntity.java
Labels: feat

#111 [#110] FAQ 등록, 수정, 삭제, 조회 API 개발
  admin/src/main/java/com/mangoboss/admin/api/controller/faq/FaqController.java
  admin/src/main/java/com/mangoboss/admin/api/facade/faq/FaqFacade.java
  admin/src/main/java/com/mangoboss/admin/common/exception/CustomErrorInfo.java
  admin/src/main/java/com/mangoboss/admin/domain/repository/FaqRepository.java
  admin/src/main/java/com/mangoboss/admin/domain/service/FaqService.java
  admin/src/main/java/com/mangoboss/admin/dto/faq/request/FaqCreateRequest.java
  admin/src/main/java/com/mangoboss/admin/dto/faq/request/FaqUpdateRequest.java
  admin/src/main/java/com/mangoboss/admin/dto/faq/response/FaqResponse.java
  admin/src/main/java/com/mangoboss/admin/infra/persistence/FaqRepositoryImpl.java
  storage/src/main/java/com/mangoboss/storage/faq/FaqCategory.java
  storage/src/main/java/com/mangoboss/storage/faq/FaqEntity.java
  storage/src/main/java/com/mangoboss/storage/faq/FaqJpaRepository.java
Labels: feat

#115 [#112] 사장 서비스 구독 기능 개발
  .github/workflows/cd-dev.yml
  app/src/main/java/com/mangoboss/app/api/controller/billing/BillingController.java
  app/src/main/java/com/mangoboss/app/api/controller/subscription/SubscriptionController.java
  app/src/main/java/com/mangoboss/app/api/facade/billing/BillingFacade.java
  app/src/main/java/com/mangoboss/app/api/facade/subscription/SubscriptionFacade.java
  app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
  app/src/main/java/com/mangoboss/app/domain/repository/BillingRepository.java
  app/src/main/java/com/mangoboss/app/domain/repository/SubscriptionRepository.java
  app/src/main/java/com/mangoboss/app/domain/service/billing/BillingService.java
  app/src/main/java/com/mangoboss/app/domain/service/subscription/SubscriptionService.java
  app/src/main/java/com/mangoboss/app/dto/billing/BillingRegisterRequest.java
  app/src/main/java/com/mangoboss/app/dto/subscription/request/SubscriptionCreateRequest.java
  app/src/main/java/com/mangoboss/app/dto/subscription/response/BillingCustomerKeyResponse.java
  app/src/main/java/com/mangoboss/app/dto/subscription/response/SubscriptionResponse.java
  app/src/main/java/com/mangoboss/app/external/tosspayment/TossPaymentClient.java
  app/src/main/java/com/mangoboss/app/infra/persistence/BillingRepositoryImpl.java
  app/src/main/java/com/mangoboss/app/infra/persistence/SubscriptionRepositoryImpl.java
  app/src/main/resources/application-dev.yml
  batch/src/main/java/com/mangoboss/batch/billing/AutoBillingScheduler.java
  batch/src/main/java/com/mangoboss/batch/billing/AutoBillingService.java
  batch/src/main/java/com/mangoboss/batch/billing/BillingRepository.java
  batch/src/main/java/com/mangoboss/batch/billing/BillingRepositoryImpl.java
  batch/src/main/java/com/mangoboss/batch/billing/SubscriptionBillingHandler.java
  batch/src/main/java/com/mangoboss/batch/billing/SubscriptionOrderRepository.java
  batch/src/main/java/com/mangoboss/batch/billing/SubscriptionOrderRepositoryImpl.java
  batch/src/main/java/com/mangoboss/batch/billing/SubscriptionRepository.java
  batch/src/main/java/com/mangoboss/batch/billing/SubscriptionRepositoryImpl.java
  batch/src/main/java/com/mangoboss/batch/billing/TossPaymentClient.java
  batch/src/main/java/com/mangoboss/batch/billing/UserRepository.java
  batch/src/main/java/com/mangoboss/batch/billing/UserRepositoryImpl.java
  batch/src/main/resources/application.yml
  storage/src/main/java/com/mangoboss/storage/billing/BillingEntity.java
  storage/src/main/java/com/mangoboss/storage/billing/BillingJpaRepository.java
  storage/src/main/java/com/mangoboss/storage/subscription/PaymentStatus.java
  storage/src/main/java/com/mangoboss/storage/subscription/PlanType.java
  storage/src/main/java/com/mangoboss/storage/subscription/SubscriptionEntity.java
  storage/src/main/java/com/mangoboss/storage/subscription/SubscriptionJpaRepository.java
  storage/src/main/java/com/mangoboss/storage/subscription/SubscriptionOrderEntity.java
  storage/src/main/java/com/mangoboss/storage/subscription/SubscriptionOrderJpaRepository.java
Labels: config, feat, ci/cd

#116 feat: 센트리 모니터링 추가 (#109)
  app/build.gradle
  app/src/main/java/com/mangoboss/app/api/controller/TestController.java
  app/src/main/java/com/mangoboss/app/common/exception/GlobalExceptionHandler.java
  app/src/main/resources/application.yml
Labels: feat

#123 [#122] 구독 관련 코드 변경
  admin/src/main/java/com/mangoboss/admin/domain/repository/SubscriptionRepository.java
  admin/src/main/java/com/mangoboss/admin/domain/service/AdminDashBoardService.java
  admin/src/main/java/com/mangoboss/admin/dto/dashboard/SubscriptionStatisticsResponse.java
  admin/src/main/java/com/mangoboss/admin/infra/persistence/SubscriptionRepositoryImpl.java
  app/src/main/java/com/mangoboss/app/api/controller/billing/BillingController.java
  app/src/main/java/com/mangoboss/app/api/facade/billing/BillingFacade.java
  app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
  app/src/main/java/com/mangoboss/app/common/util/CardIssuerResolver.java
  app/src/main/java/com/mangoboss/app/domain/service/billing/BillingService.java
  app/src/main/java/com/mangoboss/app/dto/billing/request/BillingRegisterRequest.java
  app/src/main/java/com/mangoboss/app/dto/billing/response/BillingCardInfoResponse.java
  app/src/main/java/com/mangoboss/app/dto/subscription/response/SubscriptionResponse.java
  batch/src/main/java/com/mangoboss/batch/billing/AutoBillingService.java
  batch/src/main/java/com/mangoboss/batch/billing/SubscriptionBillingHandler.java
  batch/src/main/java/com/mangoboss/batch/billing/SubscriptionRepository.java
  batch/src/main/java/com/mangoboss/batch/billing/SubscriptionRepositoryImpl.java
  storage/src/main/java/com/mangoboss/storage/billing/BillingEntity.java
  storage/src/main/java/com/mangoboss/storage/subscription/PlanType.java
  storage/src/main/java/com/mangoboss/storage/subscription/SubscriptionEntity.java
  storage/src/main/java/com/mangoboss/storage/subscription/SubscriptionJpaRepository.java
Labels: refactor

#124 release: dev -> main
  admin/src/main/java/com/mangoboss/admin/domain/repository/SubscriptionRepository.java
  admin/src/main/java/com/mangoboss/admin/domain/service/AdminDashBoardService.java
  admin/src/main/java/com/mangoboss/admin/dto/dashboard/SubscriptionStatisticsResponse.java
  admin/src/main/java/com/mangoboss/admin/infra/persistence/SubscriptionRepositoryImpl.java
  app/src/main/java/com/mangoboss/app/api/controller/billing/BillingController.java
  app/src/main/java/com/mangoboss/app/api/facade/billing/BillingFacade.java
  app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
  app/src/main/java/com/mangoboss/app/common/util/CardIssuerResolver.java
  app/src/main/java/com/mangoboss/app/domain/service/billing/BillingService.java
  app/src/main/java/com/mangoboss/app/dto/billing/request/BillingRegisterRequest.java
  app/src/main/java/com/mangoboss/app/dto/billing/response/BillingCardInfoResponse.java
  app/src/main/java/com/mangoboss/app/dto/subscription/response/SubscriptionResponse.java
  app/src/main/resources/application-dev.yml
  app/src/main/resources/application.yml
  app/src/main/resources/data.sql
  batch/src/main/java/com/mangoboss/batch/billing/AutoBillingService.java
  batch/src/main/java/com/mangoboss/batch/billing/SubscriptionBillingHandler.java
  batch/src/main/java/com/mangoboss/batch/billing/SubscriptionRepository.java
  batch/src/main/java/com/mangoboss/batch/billing/SubscriptionRepositoryImpl.java
  storage/src/main/java/com/mangoboss/storage/billing/BillingEntity.java
  storage/src/main/java/com/mangoboss/storage/subscription/PlanType.java
  storage/src/main/java/com/mangoboss/storage/subscription/SubscriptionEntity.java
  storage/src/main/java/com/mangoboss/storage/subscription/SubscriptionJpaRepository.java
Labels: fix, config

#126 [#122] 사장 구독 현황, 결제 수단 없을 때 null DTO 반환
  app/src/main/java/com/mangoboss/app/api/facade/subscription/SubscriptionFacade.java
  app/src/main/java/com/mangoboss/app/domain/repository/SubscriptionRepository.java
  app/src/main/java/com/mangoboss/app/domain/service/billing/BillingService.java
  app/src/main/java/com/mangoboss/app/domain/service/subscription/SubscriptionService.java
  app/src/main/java/com/mangoboss/app/infra/persistence/SubscriptionRepositoryImpl.java
Labels: refactor

#129 [#128] 로그아웃 기능 개발
  app/src/main/java/com/mangoboss/app/api/controller/auth/AuthController.java
  app/src/main/java/com/mangoboss/app/api/facade/auth/AuthFacade.java
  app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
  app/src/main/java/com/mangoboss/app/common/util/JwtUtil.java
  app/src/main/java/com/mangoboss/app/domain/service/auth/AuthService.java
Labels: feat

#133 [#81] 알바생이 사장님에게 보고사항 작성 시 사장님에게 알림 전송 기능 개발
  app/src/main/java/com/mangoboss/app/api/facade/workreport/StaffWorkReportFacade.java
  app/src/main/java/com/mangoboss/app/domain/service/notification/NotificationService.java
  storage/src/main/java/com/mangoboss/storage/notification/NotificationEntity.java
  storage/src/main/java/com/mangoboss/storage/notification/NotificationJpaRepository.java
  storage/src/main/java/com/mangoboss/storage/notification/NotificationType.java
Labels: refactor, feat

#137 release: dev -> main
  app/src/main/resources/data.sql
Labels: fix

#140 [Release] 알바생 보고사항 작성자 정보 잘못 표시되는 버그 수정
  app/src/main/java/com/mangoboss/app/api/facade/workreport/StaffWorkReportFacade.java
Labels: fix

#141 [Release] payroll summary null 에러 해결
  app/src/main/java/com/mangoboss/app/api/facade/payroll/BossPayrollFacade.java
  app/src/main/java/com/mangoboss/app/dto/payroll/response/TransferSummaryResponse.java
Labels: fix

#142 [Release] 알바생 업무 완료 시 TaskLog에 잘못된 staffId 저장 문제 수정 (hotfix)
  app/src/main/java/com/mangoboss/app/api/facade/task/StaffTaskFacade.java
Labels: fix
