Repository Mango-Butter/dev-back, pull requests merged in 2025-05, with the labels that each got.

#28 [#24] 근로계약서 작성 및 조회 API 개발
  .github/workflows/cd.yml
  app/build.gradle
  app/src/main/java/com/mangoboss/app/api/controller/contract/BossContractController.java
  app/src/main/java/com/mangoboss/app/api/controller/contract/StaffContractController.java
  app/src/main/java/com/mangoboss/app/api/facade/contract/BossContractFacade.java
  app/src/main/java/com/mangoboss/app/api/facade/contract/StaffContractFacade.java
  app/src/main/java/com/mangoboss/app/common/config/S3Config.java
  app/src/main/java/com/mangoboss/app/common/config/S3PreSignerConfig.java
  app/src/main/java/com/mangoboss/app/common/constant/ContentType.java
  app/src/main/java/com/mangoboss/app/common/constant/S3FileType.java
  app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
  app/src/main/java/com/mangoboss/app/common/security/AesEncryptor.java
  app/src/main/java/com/mangoboss/app/common/util/JsonConverter.java
  app/src/main/java/com/mangoboss/app/common/util/PdfGenerator.java
  app/src/main/java/com/mangoboss/app/common/util/S3FileManager.java
  app/src/main/java/com/mangoboss/app/domain/repository/ContractRepository.java
  app/src/main/java/com/mangoboss/app/domain/service/contract/ContractHtmlGenerator.java
  app/src/main/java/com/mangoboss/app/domain/service/contract/ContractService.java
  app/src/main/java/com/mangoboss/app/domain/service/contract/SignatureImageDecoder.java
  app/src/main/java/com/mangoboss/app/dto/contract/request/ContractCreateRequest.java
  app/src/main/java/com/mangoboss/app/dto/contract/request/ContractData.java
  app/src/main/java/com/mangoboss/app/dto/contract/request/ContractDataInput.java
  app/src/main/java/com/mangoboss/app/dto/contract/request/ContractSignRequest.java
  app/src/main/java/com/mangoboss/app/dto/contract/request/SignatureUploadRequest.java
  app/src/main/java/com/mangoboss/app/dto/contract/request/WorkSchedule.java
  app/src/main/java/com/mangoboss/app/dto/contract/response/ContractDetailResponse.java
  app/src/main/java/com/mangoboss/app/dto/contract/response/ContractResponse.java
  app/src/main/java/com/mangoboss/app/dto/contract/response/DownloadPreSignedUrlResponse.java
  app/src/main/java/com/mangoboss/app/dto/contract/response/SignatureUploadResponse.java
  app/src/main/java/com/mangoboss/app/dto/contract/response/ViewPreSignedUrlResponse.java
  app/src/main/java/com/mangoboss/app/infra/persistence/ContractRepositoryImpl.java
  app/src/main/resources/application-dev.yml
  app/src/main/resources/application-test.yml
  app/src/main/resources/templates/contract-template.html
  storage/src/main/java/com/mangoboss/storage/contract/ContractEntity.java
  storage/src/main/java/com/mangoboss/storage/contract/ContractJpaRepository.java
  storage/src/main/java/com/mangoboss/storage/contract/ContractStatus.java
Labels: build, config, feat, ci/cd

#31 [#30] 사장이 알바생 근무 요일, 근태 요약 조회 기능 개발
  app/src/main/java/com/mangoboss/app/api/controller/dashboard/BossDashboardController.java
  app/src/main/java/com/mangoboss/app/api/facade/dashboard/BossDashboardFacade.java
  app/src/main/java/com/mangoboss/app/domain/repository/AttendanceRepository.java
  app/src/main/java/com/mangoboss/app/domain/repository/RegularGroupRepository.java
  app/src/main/java/com/mangoboss/app/domain/service/attendance/AttendanceService.java
  app/src/main/java/com/mangoboss/app/domain/service/schedule/ScheduleService.java
  app/src/main/java/com/mangoboss/app/dto/dashboard/response/StaffAttendanceCountResponse.java
  app/src/main/java/com/mangoboss/app/dto/dashboard/response/StaffAttendanceSummaryResponse.java
  app/src/main/java/com/mangoboss/app/infra/persistence/AttendanceRepositoryImpl.java
  app/src/main/java/com/mangoboss/app/infra/persistence/RegularGroupRepositoryImpl.java
  storage/src/main/java/com/mangoboss/storage/attendance/AttendanceJpaRepository.java
  storage/src/main/java/com/mangoboss/storage/attendance/projection/StaffAttendanceCountProjection.java
  storage/src/main/java/com/mangoboss/storage/schedule/RegularGroupJpaRepository.java
Labels: feat

#34 [#33] 알바생 매장 정보 조회 API 개발
  app/src/main/java/com/mangoboss/app/api/controller/store/BossStoreController.java
  app/src/main/java/com/mangoboss/app/api/controller/store/StaffStoreController.java
  app/src/main/java/com/mangoboss/app/api/facade/store/BossStoreFacade.java
  app/src/main/java/com/mangoboss/app/api/facade/store/StaffStoreFacade.java
  app/src/main/java/com/mangoboss/app/domain/repository/StoreRepository.java
  app/src/main/java/com/mangoboss/app/domain/service/store/StoreService.java
  app/src/main/java/com/mangoboss/app/dto/store/response/BossStoreInfoResponse.java
  app/src/main/java/com/mangoboss/app/dto/store/response/StaffStoreInfoResponse.java
  app/src/main/java/com/mangoboss/app/infra/persistence/StoreRepositoryImpl.java
  storage/src/main/java/com/mangoboss/storage/store/StoreJpaRepository.java
Labels: feat

#40 [#24] 근로계약서 알바생 서명 완료시 스케줄 자동 생성 로직 구현
  app/src/main/java/com/mangoboss/app/api/facade/contract/StaffContractFacade.java
  app/src/main/java/com/mangoboss/app/domain/service/contract/ContractService.java
Labels: feat

#41 [#22] 근로계약서 템플릿 기능 개발
  app/src/main/java/com/mangoboss/app/api/controller/contract/BossContractController.java
  app/src/main/java/com/mangoboss/app/api/facade/contract/BossContractFacade.java
  app/src/main/java/com/mangoboss/app/api/facade/contract/StaffContractFacade.java
  app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
  app/src/main/java/com/mangoboss/app/domain/repository/ContractTemplateRepository.java
  app/src/main/java/com/mangoboss/app/domain/service/contract/ContractService.java
  app/src/main/java/com/mangoboss/app/domain/service/contract/ContractTemplateService.java
  app/src/main/java/com/mangoboss/app/dto/contract/request/ContractTemplateCreateRequest.java
  app/src/main/java/com/mangoboss/app/dto/contract/request/ContractTemplateData.java
  app/src/main/java/com/mangoboss/app/dto/contract/request/ContractTemplateUpdateRequest.java
  app/src/main/java/com/mangoboss/app/dto/contract/response/ContractTemplateDetailResponse.java
  app/src/main/java/com/mangoboss/app/dto/contract/response/ContractTemplateResponse.java
  app/src/main/java/com/mangoboss/app/infra/persistence/ContractTemplateRepositoryImpl.java
  storage/src/main/java/com/mangoboss/storage/contract/ContractTemplate.java
  storage/src/main/java/com/mangoboss/storage/contract/ContractTemplateJpaRepository.java
Labels: feat

#45 [#44] 사장 제출 서류 설정 조회 및 저장 기능 개발
  app/src/main/java/com/mangoboss/app/api/controller/document/BossDocumentController.java
  app/src/main/java/com/mangoboss/app/api/facade/document/BossDocumentFacade.java
  app/src/main/java/com/mangoboss/app/api/facade/store/BossStoreFacade.java
  app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
  app/src/main/java/com/mangoboss/app/domain/repository/RequiredDocumentRepository.java
  app/src/main/java/com/mangoboss/app/domain/service/document/RequiredDocumentService.java
  app/src/main/java/com/mangoboss/app/dto/document/request/RequiredDocumentCreateRequest.java
  app/src/main/java/com/mangoboss/app/dto/document/response/RequiredDocumentResponse.java
  app/src/main/java/com/mangoboss/app/infra/persistence/RequiredDocumentRepositoryImpl.java
  app/src/main/resources/data.sql
  storage/src/main/java/com/mangoboss/storage/document/DocumentType.java
  storage/src/main/java/com/mangoboss/storage/document/RequiredDocumentEntity.java
  storage/src/main/java/com/mangoboss/storage/document/RequiredDocumentJpaRepository.java
Labels: feat

#43 [#42] 알바생 근로계약서 목록 조회 기능 개발
  app/src/main/java/com/mangoboss/app/api/controller/contract/StaffContractController.java
  app/src/main/java/com/mangoboss/app/api/facade/contract/StaffContractFacade.java
  app/src/main/java/com/mangoboss/app/domain/repository/ContractRepository.java
  app/src/main/java/com/mangoboss/app/domain/service/contract/ContractService.java
  app/src/main/java/com/mangoboss/app/dto/contract/response/StaffContractListResponse.java
  app/src/main/java/com/mangoboss/app/infra/persistence/ContractRepositoryImpl.java
  storage/src/main/java/com/mangoboss/storage/contract/ContractJpaRepository.java
Labels: feat

#48 [#47] 사장이 보관된 서류를 조회, 삭제, 다운로드하는 API 개발
  app/src/main/java/com/mangoboss/app/api/controller/document/BossDocumentController.java
  app/src/main/java/com/mangoboss/app/api/facade/document/BossDocumentFacade.java
  app/src/main/java/com/mangoboss/app/api/facade/document/StaffDocumentFacade.java
  app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
  app/src/main/java/com/mangoboss/app/domain/repository/DocumentRepository.java
  app/src/main/java/com/mangoboss/app/domain/service/document/DocumentService.java
  app/src/main/java/com/mangoboss/app/infra/persistence/DocumentRepositoryImpl.java
Labels: feat

#54 [#47] 사장이 알바생 근로계약서 목록 조회 API 개발
  app/src/main/java/com/mangoboss/app/api/controller/attendance/BossAttendanceController.java
  app/src/main/java/com/mangoboss/app/api/controller/contract/BossContractController.java
  app/src/main/java/com/mangoboss/app/api/facade/contract/BossContractFacade.java
  app/src/main/java/com/mangoboss/app/domain/repository/ContractRepository.java
  app/src/main/java/com/mangoboss/app/domain/service/contract/ContractService.java
  app/src/main/java/com/mangoboss/app/dto/contract/response/ContractSummaryResponse.java
  app/src/main/java/com/mangoboss/app/infra/persistence/ContractRepositoryImpl.java
  storage/src/main/java/com/mangoboss/storage/contract/ContractEntity.java
  storage/src/main/java/com/mangoboss/storage/contract/ContractJpaRepository.java
  storage/src/main/java/com/mangoboss/storage/contract/ContractStatus.java
Labels: feat

#55 [#52] 알바생 본인이 제출한 서류 목록과 제출 상태 조회 API 개발
  app/src/main/java/com/mangoboss/app/api/controller/document/StaffDocumentController.java
  app/src/main/java/com/mangoboss/app/api/facade/document/StaffDocumentFacade.java
  app/src/main/java/com/mangoboss/app/domain/repository/DocumentRepository.java
  app/src/main/java/com/mangoboss/app/domain/service/document/DocumentService.java
  app/src/main/java/com/mangoboss/app/dto/document/response/MyDocumentStatusResponse.java
  app/src/main/java/com/mangoboss/app/infra/persistence/DocumentRepositoryImpl.java
  storage/src/main/java/com/mangoboss/storage/document/DocumentJpaRepository.java
Labels: feat

#59 [#58] 캘린더에서 알바생이 다른 알바생 전체 근무 일정 조회 API 개발
  app/src/main/java/com/mangoboss/app/api/controller/calendar/BossCalendarController.java
  app/src/main/java/com/mangoboss/app/api/controller/calendar/StaffCalendarController.java
  app/src/main/java/com/mangoboss/app/api/facade/calendar/BossCalendarFacade.java
  app/src/main/java/com/mangoboss/app/api/facade/calendar/StaffCalendarFacade.java
Labels: feat

#57 [#39] 서류 업로드 시 중복 업로드 방지 로직 추가
  app/src/main/java/com/mangoboss/app/api/facade/document/StaffDocumentFacade.java
  app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
  app/src/main/java/com/mangoboss/app/domain/repository/DocumentRepository.java
  app/src/main/java/com/mangoboss/app/domain/service/document/DocumentService.java
  app/src/main/java/com/mangoboss/app/infra/persistence/DocumentRepositoryImpl.java
  storage/src/main/java/com/mangoboss/storage/document/DocumentJpaRepository.java
Labels: feat

#62 [#61] 알바생 본인 근태 기록 월별 조회, 특정 근태 기록 상세 조회
  app/src/main/java/com/mangoboss/app/api/controller/attendance/StaffAttendanceController.java
  app/src/main/java/com/mangoboss/app/api/facade/attendance/StaffAttendanceFacade.java
  app/src/main/java/com/mangoboss/app/domain/service/schedule/ScheduleService.java
Labels: feat

#64 [#37] 확정된 급여 조회 기능 개발
  app/src/main/java/com/mangoboss/app/api/controller/payroll/BossPayrollController.java
  app/src/main/java/com/mangoboss/app/api/facade/payroll/BossPayrollFacade.java
  app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
  app/src/main/java/com/mangoboss/app/domain/repository/PayrollRepository.java
  app/src/main/java/com/mangoboss/app/domain/service/payroll/PayrollService.java
  app/src/main/java/com/mangoboss/app/domain/service/payroll/PayrollSettingService.java
  app/src/main/java/com/mangoboss/app/dto/payroll/response/PayrollEstimatedResponse.java
  app/src/main/java/com/mangoboss/app/dto/payroll/response/PayrollSimpleResponse.java
  app/src/main/java/com/mangoboss/app/infra/persistence/PayrollRepositoryImpl.java
  storage/src/main/java/com/mangoboss/storage/payroll/PayrollJpaRepository.java
Labels: refactor, feat

#67 [#37] 사장 계좌 삭제 기능 개발
  app/src/main/java/com/mangoboss/app/api/controller/payroll/BossPayrollController.java
  app/src/main/java/com/mangoboss/app/api/facade/payroll/BossPayrollFacade.java
  app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
  app/src/main/java/com/mangoboss/app/domain/repository/TransferAccountRepository.java
  app/src/main/java/com/mangoboss/app/domain/service/payroll/PayrollSettingService.java
  app/src/main/java/com/mangoboss/app/infra/persistence/TransferAccountRepositoryImpl.java
Labels: feat

#75 [#70] 사장은 업무 체크리스트의 진행 상황을 상시 조회가 가능하다.
  app/src/main/java/com/mangoboss/app/api/controller/task/BossTaskController.java
  app/src/main/java/com/mangoboss/app/api/controller/task/StaffTaskController.java
  app/src/main/java/com/mangoboss/app/api/facade/task/BossTaskFacade.java
  app/src/main/java/com/mangoboss/app/api/facade/task/StaffTaskFacade.java
  app/src/main/java/com/mangoboss/app/domain/repository/TaskLogRepository.java
  app/src/main/java/com/mangoboss/app/domain/repository/TaskRepository.java
  app/src/main/java/com/mangoboss/app/domain/service/task/TaskService.java
  app/src/main/java/com/mangoboss/app/infra/persistence/TaskLogRepositoryImpl.java
  app/src/main/java/com/mangoboss/app/infra/persistence/TaskRepositoryImpl.java
  storage/src/main/java/com/mangoboss/storage/task/TaskLogJpaRepository.java
  storage/src/main/java/com/mangoboss/storage/task/TaskRoutineJpaRepository.java
Labels: feat

#76 [#47] 근로계약서 PDF 무결성 검증 로직 추가
  app/src/main/java/com/mangoboss/app/api/facade/contract/BossContractFacade.java
  app/src/main/java/com/mangoboss/app/api/facade/contract/StaffContractFacade.java
  app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
  app/src/main/java/com/mangoboss/app/common/util/DigestUtil.java
  app/src/main/java/com/mangoboss/app/common/util/S3FileManager.java
  app/src/main/java/com/mangoboss/app/domain/service/contract/ContractService.java
  storage/src/main/java/com/mangoboss/storage/contract/ContractEntity.java
Labels: feat

#83 [#82] S3 버킷 속성 분리 및 관련 로직 리팩토링
  app/src/main/java/com/mangoboss/app/api/facade/contract/BossContractFacade.java
  app/src/main/java/com/mangoboss/app/api/facade/contract/StaffContractFacade.java
  app/src/main/java/com/mangoboss/app/api/facade/document/BossDocumentFacade.java
  app/src/main/java/com/mangoboss/app/api/facade/document/StaffDocumentFacade.java
  app/src/main/java/com/mangoboss/app/api/facade/task/BossTaskFacade.java
  app/src/main/java/com/mangoboss/app/api/facade/task/StaffTaskFacade.java
  app/src/main/java/com/mangoboss/app/common/config/S3Config.java
  app/src/main/java/com/mangoboss/app/common/constant/ContentType.java
  app/src/main/java/com/mangoboss/app/common/constant/S3FileType.java
  app/src/main/java/com/mangoboss/app/common/util/S3FileManager.java
  app/src/main/java/com/mangoboss/app/common/util/S3PreSignedUrlManager.java
  app/src/main/java/com/mangoboss/app/domain/service/contract/ContractService.java
  app/src/main/java/com/mangoboss/app/domain/service/document/DocumentService.java
  app/src/main/java/com/mangoboss/app/domain/service/task/TaskService.java
  storage/src/main/java/com/mangoboss/storage/metadata/S3FileType.java
Labels: refactor, config

#85 [#82] FCM 연동
  .github/workflows/cd.yml
  .gitignore
  batch/build.gradle
  batch/src/main/java/com/mangoboss/batch/infra/FcmInitializer.java
  batch/src/main/resources/application.yml
Labels: config, feat, ci/cd
